### ISSUE TITLE
Crashes on dedicated servers

### ISSUE THREAD

**Issue by dvitski** [Duskitty/kittycamp#2]
### Issue
At [`io.github.duskitty.kittycamp.Main#L21`](https://github.com/Duskitty/kittycamp/blob/8feb742af01cd6957160891fb5bc2e42c585f8a2/src/main/java/io/github/duskitty/kittycamp/Main.java#L21), client code is ran on the server, causing a dedicated server to crash.

### Fix
Replace [`io.github.duskitty.kittycamp.Main_Client#L13`](https://github.com/Duskitty/kittycamp/blob/8feb742af01cd6957160891fb5bc2e42c585f8a2/src/main/java/io/github/duskitty/kittycamp/Main_Client.java#L13) with [`io.github.duskitty.kittycamp.Main#L21`](https://github.com/Duskitty/kittycamp/blob/8feb742af01cd6957160891fb5bc2e42c585f8a2/src/main/java/io/github/duskitty/kittycamp/Main.java#L21) and delete the line in `Main`

**Comment by Duskitten** [comment]
this is fixed now
